set(GGUI_MINGW_TRIPLET "x86_64-w64-mingw32" CACHE STRING "MinGW-w64 target triplet")

set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

find_program(GGUI_MINGW_C_COMPILER NAMES "${GGUI_MINGW_TRIPLET}-gcc" REQUIRED)
find_program(GGUI_MINGW_CXX_COMPILER NAMES "${GGUI_MINGW_TRIPLET}-g++" REQUIRED)
find_program(GGUI_MINGW_RC_COMPILER NAMES "${GGUI_MINGW_TRIPLET}-windres" REQUIRED)
set(CMAKE_C_COMPILER "${GGUI_MINGW_C_COMPILER}" CACHE FILEPATH "MinGW-w64 C compiler" FORCE)
set(CMAKE_CXX_COMPILER "${GGUI_MINGW_CXX_COMPILER}" CACHE FILEPATH "MinGW-w64 C++ compiler" FORCE)
set(CMAKE_RC_COMPILER "${GGUI_MINGW_RC_COMPILER}" CACHE FILEPATH "MinGW-w64 resource compiler" FORCE)

set(CMAKE_FIND_ROOT_PATH "/usr/${GGUI_MINGW_TRIPLET}" "/usr/local/${GGUI_MINGW_TRIPLET}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(BUILD_SHARED_LIBS OFF CACHE BOOL "Build static libraries" FORCE)
set(NEED_LIBRT FALSE CACHE INTERNAL "MinGW has clock_gettime without librt" FORCE)
set(CMAKE_FIND_LIBRARY_SUFFIXES ".a" ".lib")
set(CMAKE_EXE_LINKER_FLAGS_INIT "-static -static-libgcc -static-libstdc++")
