#pragma once

#ifndef IMGUI_DEFINE_MATH_OPERATORS
#define IMGUI_DEFINE_MATH_OPERATORS 1
#endif

#if IMGUI_BUILD_TESTING
#define IMGUI_DISABLE_STB_IMAGE_WRITE_IMPLEMENTATION 1
#define IMGUI_STB_IMAGE_WRITE_FILENAME "stb_image_write.h"
#define IMGUI_TEST_ENGINE_ENABLE_IMPLOT 0
#define IMGUI_TEST_ENGINE_ENABLE_STD_FUNCTION 1
#define IMGUI_TEST_ENGINE_ENABLE_COROUTINE_STDTHREAD_IMPL 1
#include <imgui_te_imconfig.h>
#define IM_ASSERT(_EXPR) IM_TEST_ENGINE_ASSERT(_EXPR)
#endif
